### ISSUE TITLE
Does this plugin also work with the UE Megaboom?

### ISSUE THREAD

**Issue by jorgdeboer** [alessandroaime/homebridge-ueboom#2]
im getting the following error:

[1/25/2020, 1:02:22 PM] [Jorg's Speaker] Setting speaker to true
stderr: connect: Device or resource busy (16)
stderr: connect error: Connection refused (111)

or

stderr: connect error: Function not implemented (38)

**Comment by alessandroaime** [comment]
Unfortunately I don’t have a Megaboom to test the plugin with, but it should work since the feature is the same across all the UE Boom-family speakers.

Those messages you see are (if I remember correctly) respectively when turning on the speaker and when the speaker is already turned on. As I’m not home at the moment so I can’t double check, I will do it tomorrow evening or next week and will let you know.

Are you using the latest version (0.0.3)?

**Comment by jorgdeboer** [comment]
Thanks for the response, sure no hurries.

Yes, both the UE Megaboom as the plugin are on the latest versions. In addition, below my config:

{
            "accessory": "UEBoomSpeaker",
            "name": "Jorg's Speaker",
            "speaker": "88:C6:26:D0:F7:59",
            "host": "D4A33D9B0844"
        }

Now I am only getting the Function not Implemented error (made sure the UE is off):
stderr: connect error: Function not implemented (38)

Please let me know if I can troubleshoot anything.

**Comment by alessandroaime** [comment]
I looked into it but I haven't been able to recreate the `stderr: connect error: Function not implemented (38)` error.

You could try to follow the instructions in the README of this repo on how I was able to first connect to the speaker using PackerLogger and command line.

**Comment by jorgdeboer** [comment]
Thanks for coming back to this. I will have a look.
